ServerName localhost
<Directory /var/www/html>
    Options -Indexes
    AllowOverride None
</Directory>
<FilesMatch "^(set-up-database\.php|.*\.inc)$">
    Require all denied
</FilesMatch>
<Directory /var/www/html/passwords>
    Require all denied
</Directory>
